services:
  db-ozon:
    image: postgres:15
    container_name: db-ozon
    environment:
      - POSTGRES_DB=study
      - POSTGRES_USER=study
      - POSTGRES_PASSWORD=study
    ports:
      - 5433:5432
    volumes:
      - db-ozon-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U study -d study" ]
      interval: 5s
      timeout: 1s
      retries: 10
    restart: unless-stopped

  db-payment-service:
    image: postgres:15
    container_name: db-payment-service
    environment:
      - POSTGRES_DB=study
      - POSTGRES_USER=study
      - POSTGRES_PASSWORD=study
    ports:
      - 5434:5432
    volumes:
      - db-payment-service-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U study -d study" ]
      interval: 5s
      timeout: 1s
      retries: 10
    restart: unless-stopped

  ozon-service:
    build:
      context: .
      dockerfile: ./ozon.Dockerfile
    depends_on:
      db-ozon:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db-ozon
      - DATABASE_PORT=5432
      - SERVER_PORT=8080
      - PAYMENT_SERVICE_URL=http://payment-service:8081
      - PAYMENT_SERVICE_USERNAME=ozon-integration
      - PAYMENT_SERVICE_PASSWORD=ozon-secret
    ports:
      - 8080:8080
      - 9090:9090
    networks:
      - backend

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service.Dockerfile
    depends_on:
      db-payment-service:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db-payment-service
      - DATABASE_PORT=5432
      - SERVER_PORT=8081
    ports:
      - 8081:8081
      - 9091:9090
    networks:
      - backend

networks:
  backend:

volumes:
  db-ozon-data:
  db-payment-service-data: