spring.application.name=OZON
spring.config.import=optional:secrets.properties
server.port=2104

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5433}/${DATABASE_DB:study}
spring.datasource.username=${DATABASE_USERNAME:study}
spring.datasource.password=${DATABASE_PASSWORD:study}

spring.clients.payment-service-url=${PAYMENT_SERVICE_URL:http://localhost:8081}
spring.clients.payment-service.username=${PAYMENT_SERVICE_USERNAME:ozon-integration}
spring.clients.payment-service.password=${PAYMENT_SERVICE_PASSWORD:ozon-secret}

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true

spring.sql.init.platform=postgres

spring.liquibase.change-log=classpath:/migrations/db-changelog-master.xml

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

spring.jms.pub-sub-domain=false

logging.level.org.springframework.jms=DEBUG

management.endpoints.web.exposure.include=*

#spring.mvc.log-resolved-exception=true
#logging.level.org.springframework.web=DEBUG

springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.show-common-extensions=true

logging.level.org.springframework.data.jpa.repository.query.QueryParameterSetter=ERROR
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

activemq.username=admin
activemq.password=admin
activemq.broker-url=tcp://localhost:61616

queue.name=payment.status